name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: panpan-blog-backend
        package: '.'